
const FULL_STOCK_LIST_STRING = `360ONE,ABB,ACC,APLAPOLLO,AUBANK,ADANIENSOL,ADANIENT,ADANIGREEN,ADANIPORTS,ADANIPOWER,ATGL,ABCAPITAL,ALKEM,AMBUJACEM,APOLLOHOSP,ASHOKLEY,ASIANPAINT,ASTRAL,AUROPHARMA,DMART,AXISBANK,BSE,BAJAJ-AUTO,BAJFINANCE,BAJAJFINSV,BAJAJHLDNG,BAJAJHFL,BANKBARODA,BANKINDIA,BDL,BEL,BHARATFORG,BHEL,BPCL,BHARTIARTL,BHARTIHEXA,BIOCON,BLUESTARCO,BOSCHLTD,BRITANNIA,CGPOWER,CANBK,CHOLAFIN,CIPLA,COALINDIA,COCHINSHIP,COFORGE,COLPAL,CONCOR,COROMANDEL,CUMMINSIND,DLF,DABUR,DIVISLAB,DIXON,DRREDDY,EICHERMOT,ETERNAL,EXIDEIND,NYKAA,FEDERALBNK,FORTIS,GAIL,GMRAIRPORT,GLENMARK,GODFRYPHLP,GODREJCP,GODREJPROP,GRASIM,HCLTECH,HDFCAMC,HDFCBANK,HDFCLIFE,HAVELLS,HEROMOTOCO,HINDALCO,HAL,HINDPETRO,HINDUNILVR,HINDZINC,POWERINDIA,HUDCO,HYUNDAI,ICICIBANK,ICICIGI,IDFCFIRSTB,IRB,ITCHOTELS,ITC,INDIANB,INDHOTEL,IOC,IRCTC,IRFC,IREDA,IGL,INDUSTOWER,INDUSINDBK,NAUKRI,INFY,INDIGO,JSWENERGY,JSWSTEEL,JINDALSTEL,JIOFIN,JUBLFOOD,KEI,KPITTECH,KALYANKJIL,KOTAKBANK,LTF,LICHSGFIN,LTIM,LT,LICI,LODHA,LUPIN,MRF,M&MFIN,M&M,MANKIND,MARICO,MARUTI,MFSL,MAXHEALTH,MAZDOCK,MOTILALOFS,MPHASIS,MUTHOOTFIN,NHPC,NMDC,NTPCGREEN,NTPC,NATIONALUM,NESTLEIND,OBEROIRLTY,ONGC,OIL,PAYTM,OFSS,POLICYBZR,PIIND,PAGEIND,PATANJALI,PERSISTENT,PHOENIXLTD,PIDILITIND,POLYCAB,PFC,POWERGRID,PREMIERENE,PRESTIGE,PNB,RECLTD,RVNL,RELIANCE,SBICARD,SBILIFE,SRF,MOTHERSON,SHREECEM,SHRIRAMFIN,ENRIN,SIEMENS,SOLARINDS,SONACOMS,SBIN,SAIL,SUNPHARMA,SUPREMEIND,SUZLON,SWIGGY,TVSMOTOR,TATACOMM,TCS,TATACONSUM,TATAELXSI,TMPV,TATAPOWER,TATASTEEL,TATATECH,TECHM,TITAN,TORNTPHARM,TORNTPOWER,TRENT,TIINDIA,UPL,ULTRACEMCO,UNIONBANK,UNITDSPR,VBL,VEDL,VMM,IDEA,VOLTAS,WAAREEENER,WIPRO,YESBANK,ZYDUSLIFE`;

const STORAGE_KEY_IDEAS = 'aitrade_ideas_watchlist';
const STORAGE_KEY_ENGINE = 'aitrade_engine_universe';

const FULL_LIST_ARRAY = FULL_STOCK_LIST_STRING.split(',').map(s => s.trim().toUpperCase() + '.NS');

export const getFullUniverse = () => FULL_LIST_ARRAY;

export const getIdeasWatchlist = (): string[] => {
    const saved = localStorage.getItem(STORAGE_KEY_IDEAS);
    return saved ? JSON.parse(saved) : FULL_LIST_ARRAY;
};

export const saveIdeasWatchlist = (list: string[]) => {
    localStorage.setItem(STORAGE_KEY_IDEAS, JSON.stringify(list));
};

export const getEngineUniverse = (): string[] => {
    const saved = localStorage.getItem(STORAGE_KEY_ENGINE);
    return saved ? JSON.parse(saved) : FULL_LIST_ARRAY;
};

export const saveEngineUniverse = (list: string[]) => {
    localStorage.setItem(STORAGE_KEY_ENGINE, JSON.stringify(list));
};

export const checkAndRefreshStockList = async (): Promise<string[]> => {
    return getIdeasWatchlist();
};
